// Bug spec generator — /loop-debug --log-bug <name>
// Contract: internal/log-bug-spec.md (Phase 0 approved)
// Tests: test/bug-spec.test.ts (unit) + test/extension.test.ts (command level)

import { writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

/**
 * Lowercase; each run of chars not matching [a-z0-9] → single "-"; trim
 * leading/trailing "-". Pinned: "   " → "".
 */
export function slugBugName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * The 5 emitted customTypes (closed inventory — see spec Problem table).
 * No `loop-gate` (dead, no producer), no `loop-event` (not started).
 */
const EMITTED_TYPES = [
  "loop-debug",
  "loop-state",
  "loop-refusal",
  "loop-negotiate",
  "loop-dispute",
] as const;

/**
 * Payload from `entry.data`; if data is absent, fall back to the entry's
 * top level (robust to both envelope directions).
 */
function entryPayload(e: Record<string, unknown>): Record<string, unknown> {
  const data = e["data"];
  return data != null ? (data as Record<string, unknown>) : e;
}

/**
 * ts resolution, in order: `data.ts` (number, epoch ms → ISO) → top-level
 * `timestamp` (string, used as-is) → "-".
 */
function entryTs(
  e: Record<string, unknown>,
  payload: Record<string, unknown>,
): string {
  if (typeof payload["ts"] === "number") {
    return new Date(payload["ts"] as number).toISOString();
  }
  if (typeof e["timestamp"] === "string") {
    return e["timestamp"];
  }
  return "-";
}

/**
 * Pure. One formatted line per emitted-type entry, in input order (no
 * re-sort). Filter + formats verbatim-pinned in internal/log-bug-spec.md.
 */
export function extractLoopLogs(entries: unknown[]): string[] {
  return entries
    .filter((raw): raw is Record<string, unknown> => {
      if (raw == null || typeof raw !== "object") return false;
      const e = raw as Record<string, unknown>;
      return (
        e["type"] === "custom" &&
        (EMITTED_TYPES as readonly string[]).includes(e["customType"] as string)
      );
    })
    .map((e) => {
      const payload = entryPayload(e);
      const ts = entryTs(e, payload);
      switch (e["customType"]) {
        case "loop-debug":
          return `[${ts}] [debug] ${payload["msg"]}`;
        case "loop-state":
          return `[${ts}] [state] phase=${payload["phase"]} round=${payload["round"]}`;
        case "loop-refusal":
          return payload["path"] != null
            ? `[${ts}] [refusal] ${payload["phase"]}: blocked write to ${payload["path"]}`
            : `[${ts}] [refusal] ${payload["phase"]}: blocked ${payload["tool"]}`;
        case "loop-negotiate":
          return `[${ts}] [negotiate] ${payload["action"]}: ${String(
            payload["text"] ?? "",
          ).slice(0, 80)}`;
        case "loop-dispute":
          if (payload["claim"] != null) {
            return `[${ts}] [dispute] #${payload["disputeCount"]}: ${String(
              payload["claim"],
            ).slice(0, 80)}`;
          }
          if (payload["action"] != null) {
            return `[${ts}] [dispute] ${payload["action"]}`;
          }
          return `[${ts}] [dispute] ${JSON.stringify(payload).slice(0, 100)}`;
        default:
          return ""; // unreachable — the filter admits only the 5 emitted types
      }
    });
}

export interface BugSpecInput {
  name: string; // as given, verbatim — used in the title
  slug: string; // from slugBugName
  phase: string; // state.current.phase
  round: number; // state.current.round
  specPath: string; // state.current.specPath
  language: string; // state.current.language
  lines: string[]; // from extractLoopLogs
  now: Date;
}

/** Pure. Full markdown — template verbatim-pinned in internal/log-bug-spec.md. */
export function renderBugSpec(input: BugSpecInput): string {
  const context =
    input.phase !== "idle"
      ? `- Loop state at logging time: phase=${input.phase}, round=${input.round}, spec=${input.specPath}, language=${input.language}`
      : "- Loop state at logging time: no active loop";
  const excerpt =
    input.lines.length > 0
      ? input.lines.join("\n")
      : "(no loop events found in this session)";

  return [
    `# Bug: ${input.name}`,
    "",
    `> Generated by /loop-debug --log-bug on ${input.now.toISOString()}`,
    `> Resolve with: /loop bug-fix-${input.slug}.md`,
    "",
    "## Context",
    "",
    context,
    "",
    "## Observed problem",
    "",
    "Describe the misbehavior: what you expected, what happened, where. (Fill in before running the loop.)",
    "",
    "## Proposed fix",
    "",
    "Describe the fix approach the Writer should take. (Fill in before running the loop.)",
    "",
    "## Log excerpt",
    "",
    excerpt,
    "",
    "## Acceptance",
    "",
    "- The observed problem no longer reproduces.",
    "- <fill in: specific check>",
    "",
  ].join("\n");
}

export type BugSpecWriteResult =
  | { ok: true; path: string }
  | { ok: false; reason: "exists" | "write-failed"; message: string };

/**
 * NEVER THROWS — every failure path returns a result.
 * Evaluation order: existsSync check (reason "exists", no write) →
 * writeFileSync in try/catch (ok | reason "write-failed" with err message).
 */
export function writeBugSpec(
  cwd: string,
  slug: string,
  markdown: string,
): BugSpecWriteResult {
  const path = join(cwd, `bug-fix-${slug}.md`);
  if (existsSync(path)) {
    return { ok: false, reason: "exists", message: "" };
  }
  try {
    writeFileSync(path, markdown, "utf8");
    return { ok: true, path };
  } catch (err) {
    return {
      ok: false,
      reason: "write-failed",
      message: err instanceof Error ? err.message : String(err),
    };
  }
}
